# Generated by Django 4.0.6 on 2022-09-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_articulo_caracteristicas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='image1',
            field=models.ImageField(default='null', upload_to='fotos_articulos', verbose_name='Imagen1'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='image2',
            field=models.ImageField(default='null', upload_to='fotos_articulos', verbose_name='Imagen2'),
        ),
    ]
