# Generated by Django 4.0.6 on 2022-09-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_articulo_image1_articulo_image2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'permissions': [('can_add_articulo', 'Puede añadir articulo'), ('can_view_articulo', 'Puede ver articulo'), ('can_add_categoria', 'Puede añadir categoria'), ('can_view_categoria', 'Puede ver categoria')], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
