# Generated by Django 4.0.6 on 2022-09-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_proveedor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cif',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='CIF/NIF'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='marca',
            field=models.CharField(max_length=100, null=True, verbose_name='Marca'),
        ),
    ]
