# Generated by Django 4.0.6 on 2022-09-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_proveedor_cif_proveedor_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='marca',
        ),
    ]
