# Generated by Django 4.0.6 on 2022-09-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_remove_proveedor_cif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='articulo',
            name='image3',
            field=models.ImageField(default=None, upload_to='fotos_articulos', verbose_name='Imagen2'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cif',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='CIF/NIF'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='image1',
            field=models.ImageField(default=None, upload_to='fotos_articulos', verbose_name='Imagen1'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='image2',
            field=models.ImageField(default=None, upload_to='fotos_articulos', verbose_name='Imagen2'),
        ),
    ]
