# Generated by Django 4.0.6 on 2022-09-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_remove_articulo_cantidad_articulo_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock mínimo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='fotos_articulos', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='image1',
            field=models.ImageField(default=None, null=True, upload_to='fotos_articulos', verbose_name='Imagen1'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='image2',
            field=models.ImageField(default=None, null=True, upload_to='fotos_articulos', verbose_name='Imagen2'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='image3',
            field=models.ImageField(default=None, null=True, upload_to='fotos_articulos', verbose_name='Imagen2'),
        ),
    ]
