# Generated by Django 4.0.6 on 2022-09-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_articulo_stock_minimo_alter_articulo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='caracteristicas',
            field=models.TextField(verbose_name='Características'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripcion del producto'),
        ),
    ]
