# Generated by Django 4.0.6 on 2022-09-25 21:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_alter_articulo_caracteristicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='caracteristicas',
            field=ckeditor.fields.RichTextField(verbose_name='Características'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripcion del producto'),
        ),
    ]
